import = ["~/.config/alacritty/themes/themes/nord.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 20

decorations = "Buttonless"

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 12

#for video
# size = 35.0
